language: R
r:
- release
sudo: false
cache: packages

notifications:
  slack:
    secure: vBYKLwYhSgYulLRU4FVQ0SddnN/+OQMuBXp1gxa8MVr5ZQ2VFYIRkklePgQF6XDaP65DJwc2coNC9N55wN4Q/jDWQ0N7OA2T3npHEBaZCZ2yXaHRd8HvuQyQlpmyXO/pO0DgiUPJmvxWgfzCmEKkf3WwKLdYaYTKQj9yXPXnF+Bcaoz3h2iLLGb7VvefrIhyLI6c7XTYybQj33RdY1G2FkQx00Cps9lsrFilaRgiHPlH4JFkZ0RD3VQdAymSnpExOvBYd84vk/sIwsl0yLP9ERy0tQ80tcQFz/LpWEI/abLbiRRfWE7DkzGgLtv03NnJ8Esy2/eutLIQ1dhDu2bZWCTsLj+WBYBKaDeio0Gz220T6OSHdueffl0i6wSLTmbkIUGfgqk6cMCGHrsoZEPY9IWAuakubdpa51pXV6JVovfkqWVZb5P85lNpGjO6yewa4wm4CoEF+y3Y7x5yXz57RkAC9g97qZkyqjNyZ3mhixNOXH6DuF8J3gm6QchBSzPL9e/nbVU7nLmGqKMmh8zzDC+4BB+SKiVcOywL5Jl991eli75YcWG+DjAfJ7QqWOuQ0cAnGZdXa0wECXNNCPVt1oEih2GrEwAk2AyQL6SwfdxIkhGhBhCTgXPUX5TYWZP72wj2+DH3e72hUUrHHM3+EnkyCl3VJ/afk90IpkafMhA=
